name: bhupesh_pipeline

on: [push]
  

jobs:
  zip-files:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: maps-api-for-javascript-examples/example-template
          dest: pipeline_result.zip
